export const SET_CURRENT_CHAT_REQUEST = "SET_CURRENT_CHAT_REQUEST";
export const SET_CURRENT_CHAT_SUCCESS = "SET_CURRENT_CHAT_SUCCESS";
export const SET_CURRENT_CHAT_FAIL = "SET_CURRENT_CHAT_FAIL";

export const SET_SELECTED_CHAT_REQUEST = "SET_SELECTED_CHAT_REQUEST";
export const SET_SELECTED_CHAT_SUCCESS = "SET_SELECTED_CHAT_SUCCESS";
export const SET_SELECTED_CHAT_FAIL = "SET_SELECTED_CHAT_FAIL";
